/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplicacion;

import clases.Alquiler;
import clases.Inquilino;
import clases.Mensualidad;
import clases.Propietario;
import clases.Vivienda;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author berny
 */
public class GuanaRent extends javax.swing.JFrame {

    private ArrayList<Propietario> propietariosList = new ArrayList<>();
    private Propietarios propietarioFrame;
    private ArrayList<Inquilino> inquilinosList = new ArrayList<>();
    private Inquilinos inquilinoFrame;
    private Viviendas viviendaFrame;
    private ArrayList<Vivienda> viviendasList = new ArrayList<>();
    private Alquileres alquilerFrame;
    private ArrayList<Alquiler> alquileresList = new ArrayList<>();
    private ArrayList<Mensualidad> mensualidadesList = new ArrayList<>();
    private Mensualidades mensualidadFrame;
    private Ganancias gananciaFrame;

    /**
     * Creates new form GuanaRent
     */
    public GuanaRent() {
        initComponents();
        setTitle("Menu Principal GuanaRent");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlBotones = new javax.swing.JPanel();
        btnProietario = new javax.swing.JButton();
        btnViviendas = new javax.swing.JButton();
        btnInquilinos = new javax.swing.JButton();
        btnMensualidades = new javax.swing.JButton();
        btnGanancias = new javax.swing.JButton();
        btnAlquileres = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnInformacion = new javax.swing.JMenu();
        mntInformacion = new javax.swing.JMenuItem();
        mnCreador = new javax.swing.JMenu();
        mntCreador = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBotones.setBackground(new java.awt.Color(204, 204, 204));
        pnlBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnProietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/propietario.png"))); // NOI18N
        btnProietario.setText("Propietarios");
        btnProietario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnProietario.setPreferredSize(new java.awt.Dimension(75, 43));
        btnProietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProietarioActionPerformed(evt);
            }
        });

        btnViviendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/vivienda.png"))); // NOI18N
        btnViviendas.setText("Viviendas ");
        btnViviendas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnViviendas.setPreferredSize(new java.awt.Dimension(75, 43));
        btnViviendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViviendasActionPerformed(evt);
            }
        });

        btnInquilinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Inquilino.png"))); // NOI18N
        btnInquilinos.setText("Inquilinos");
        btnInquilinos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnInquilinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInquilinosActionPerformed(evt);
            }
        });

        btnMensualidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/mensual.png"))); // NOI18N
        btnMensualidades.setText("Mensualidades");
        btnMensualidades.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnMensualidades.setMinimumSize(new java.awt.Dimension(1, 54));
        btnMensualidades.setOpaque(true);
        btnMensualidades.setPreferredSize(new java.awt.Dimension(112, 56));
        btnMensualidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMensualidadesActionPerformed(evt);
            }
        });

        btnGanancias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ganancias.png"))); // NOI18N
        btnGanancias.setText("Ganancias");
        btnGanancias.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnGanancias.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnGanancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGananciasActionPerformed(evt);
            }
        });

        btnAlquileres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/alquiler.png"))); // NOI18N
        btnAlquileres.setText("Alquileres");
        btnAlquileres.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnAlquileres.setMinimumSize(new java.awt.Dimension(55, 55));
        btnAlquileres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlquileresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnInquilinos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViviendas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProietario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMensualidades, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlquileres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGanancias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnProietario, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViviendas, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btnInquilinos)
                .addGap(18, 18, 18)
                .addComponent(btnAlquileres, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMensualidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnGanancias)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/GuanaRent.png"))); // NOI18N

        mnInformacion.setText("Informacion");

        mntInformacion.setText("Informacion");
        mntInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntInformacionActionPerformed(evt);
            }
        });
        mnInformacion.add(mntInformacion);

        jMenuBar1.add(mnInformacion);

        mnCreador.setText("Creador");

        mntCreador.setText("Creadores");
        mntCreador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntCreadorActionPerformed(evt);
            }
        });
        mnCreador.add(mntCreador);

        jMenuBar1.add(mnCreador);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showGuanaRentFrame() {
        this.setVisible(true);
    }

    public void setPropietariosList(ArrayList<Propietario> propietariosList) {
        this.propietariosList = propietariosList;
    }

    private void btnProietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProietarioActionPerformed
        if (propietarioFrame == null) {
            propietarioFrame = new Propietarios(propietariosList, this);
        }
        propietarioFrame.setVisible(true);
    }//GEN-LAST:event_btnProietarioActionPerformed

    public void setViviendasList(ArrayList<Vivienda> viviendasList) {
        this.viviendasList = viviendasList;
    }

    private void btnViviendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViviendasActionPerformed
        if (viviendaFrame == null) {
            viviendaFrame = new Viviendas(viviendasList, propietariosList, this);
        }
        viviendaFrame.setVisible(true);
    }//GEN-LAST:event_btnViviendasActionPerformed

    public void setInquilinosList(ArrayList<Inquilino> inquilinosList) {
        this.inquilinosList = inquilinosList;
    }

    private void btnInquilinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInquilinosActionPerformed
        if (inquilinoFrame == null) {
            inquilinoFrame = new Inquilinos(inquilinosList, this);
        }
        inquilinoFrame.setVisible(true);
    }//GEN-LAST:event_btnInquilinosActionPerformed

    public void setAlquileresList(ArrayList<Alquiler> alquileresList) {
        this.alquileresList = alquileresList;
    }

    private void btnAlquileresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlquileresActionPerformed
        if (alquilerFrame == null) {
            alquilerFrame = new Alquileres(alquileresList, viviendasList, inquilinosList, this);
        }
        alquilerFrame.setVisible(true);
    }//GEN-LAST:event_btnAlquileresActionPerformed

    public void setMensualidadesList(ArrayList<Mensualidad> mensualidadesList) {
        this.mensualidadesList = mensualidadesList;
    }


    private void btnMensualidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensualidadesActionPerformed
        if (mensualidadFrame == null) {
            mensualidadFrame = new Mensualidades(mensualidadesList, alquileresList, inquilinosList, this);
        }
        mensualidadFrame.setVisible(true);
    }//GEN-LAST:event_btnMensualidadesActionPerformed

    public void setGananciasList(ArrayList<Mensualidad> mensualidadesList) {
        this.mensualidadesList = mensualidadesList;
    }

    private void btnGananciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGananciasActionPerformed
        if (gananciaFrame == null) {
            gananciaFrame = new Ganancias(mensualidadesList, alquileresList, viviendasList, inquilinosList, this);
        }
        gananciaFrame.setVisible(true);
    }//GEN-LAST:event_btnGananciasActionPerformed

    private void mntCreadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntCreadorActionPerformed

        JOptionPane.showMessageDialog(this, "Esta aplicación fue creada por [Berny Otárola] y [Jordyn Lara].");

    }//GEN-LAST:event_mntCreadorActionPerformed

    private void mntInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntInformacionActionPerformed

        String message = "<html><p style='text-align: justify; width: 300px;'>"
                + "La empresa GuanaRent es una organización que se dedica al alquiler de viviendas "
                + "en la provincia de Guanacaste. Ellos poseen clientes de 2 tipos, los primeros son los "
                + "dueños de las propiedades que se dan en alquiler, los segundos, son las personas "
                + "que arriendan una o más de las casas disponibles. GuanaRent obtiene sus ingresos "
                + "de la siguiente forma: se gana la mitad del depósito de garantía de cada alquiler "
                + "y se gana un 5% en cada mensualidad de cada casa rentada. Haga un programa "
                + "que le permita a la Empresa GuanaRent llevar el control de sus clientes, las "
                + "viviendas, los alquileres, las mensualidades y las ganancias mensuales que obtiene. "
                + "</p></html>";

        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_mntInformacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            GuanaRent guanaRentFrame = new GuanaRent();
            guanaRentFrame.setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlquileres;
    private javax.swing.JButton btnGanancias;
    private javax.swing.JButton btnInquilinos;
    private javax.swing.JButton btnMensualidades;
    private javax.swing.JButton btnProietario;
    private javax.swing.JButton btnViviendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnCreador;
    private javax.swing.JMenu mnInformacion;
    private javax.swing.JMenuItem mntCreador;
    private javax.swing.JMenuItem mntInformacion;
    private javax.swing.JPanel pnlBotones;
    // End of variables declaration//GEN-END:variables
}
